In [4]:
import pandas as pd
df=pd.read_csv("/content/tips (6).csv")
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [5]:
df.shape

(244, 11)

In [6]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [7]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [8]:
df.isnull()

total_bill    tip    sex  smoker    day   time   size  price_per_person  \
0         False  False  False   False  False  False  False             False   
1         False  False  False   False  False  False  False             False   
2         False  False  False   False  False  False  False             False   
3         False  False  False   False  False  False  False             False   
4         False  False  False   False  False  False  False             False   
..          ...    ...    ...     ...    ...    ...    ...               ...   
239       False  False  False   False  False  False  False             False   
240       False  False  False   False  False  False  False             False   
241       False  False  False   False  False  False  False             False   
242       False  False  False   False  False  False  False             False   
243       False  False  False   False  False  False  False             False   

     Payer Name  CC Number  Payment ID  
0         False      False       False  
1         False      False       False  
2         False      False       False  
3         False      False       False  
4         False      False       False  
..          ...        ...         ...  
239       False      False       False  
240       False      False       False  
241       False      False       False  
242       False      False       False  
243       False      False       False  

[244 rows x 11 columns]

In [9]:
df.isnull().sum()

total_bill          0
tip                 0
sex                 0
smoker              0
day                 0
time                0
size                0
price_per_person    0
Payer Name          0
CC Number           0
Payment ID          0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [12]:
dataset_table=pd.crosstab(df['sex'],df['smoker'],margins=True)
dataset_table

smoker   No  Yes  All
sex                  
Female   54   33   87
Male     97   60  157
All     151   93  244

In [13]:
dataset_table1=pd.crosstab(df['sex'],df['smoker'])

In [15]:
dataset_table1

smoker  No  Yes
sex            
Female  54   33
Male    97   60

In [14]:
observed_values=dataset_table1.values

In [16]:
observed_values

array([[54, 33],
       [97, 60]])

In [17]:
import seaborn as sns
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency

In [19]:
val=stats.chi2_contingency(dataset_table1)
val

Chi2ContingencyResult(statistic=0.0, pvalue=1.0, dof=1, expected_freq=array([[53.84016393, 33.15983607],
       [97.15983607, 59.84016393]]))

In [21]:
Expected_Values=val[3]
Expected_Values

array([[53.84016393, 33.15983607],
       [97.15983607, 59.84016393]])

In [22]:
no_of_rows=len(dataset_table1.iloc[0:2,0])
no_of_columns=len(dataset_table1.iloc[0,0:2])

In [24]:
ddof=(no_of_rows-1)*(no_of_columns-1)
alpha=0.05
ddof

1

In [27]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,Expected_Values)])
chi_square

array([0.00073745, 0.00119737])

In [29]:
chi_square_statistic=chi_square[0]+chi_square[1]
chi_square_statistic

0.001934818536627623

In [31]:
critical_value=chi2.ppf(1-alpha,df=ddof)
critical_value

3.841458820694124

In [33]:
if chi_square_statistic>=critical_value:
    print("Reject Ho(Null Hypothesis"),
else:
    print("Retain Ho(Null Hypothesis")


Retain Ho(Null Hypothesis
